"""
Train a custom VigilantEye UFM YOLO model.

Usage (backend venv with ultralytics installed):
  cd "D:\\BS CS\\Vigilant Eye"
  .\\backend\\venv\\Scripts\\Activate.ps1
  python ai/train_yolo.py --epochs 50

Requires labeled data under ai/dataset/ufm/ (see ai/dataset/README.md).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from ultralytics import YOLO


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Train VigilantEye UFM YOLO model")
    parser.add_argument(
        "--data",
        type=str,
        default=str(root / "dataset" / "ufm" / "data.yaml"),
        help="Path to dataset data.yaml",
    )
    parser.add_argument(
        "--base-weights",
        type=str,
        default=str(root / "weights" / "yolov8n.pt"),
        help="Starting weights (downloads yolov8n.pt on first run if missing)",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=50,
        help="Training epochs",
    )
    parser.add_argument(
        "--imgsz",
        type=int,
        default=640,
        help="Training image size",
    )
    parser.add_argument(
        "--batch",
        type=int,
        default=8,
        help="Batch size (reduce if GPU OOM)",
    )
    parser.add_argument(
        "--project",
        type=str,
        default=str(root / "runs" / "train"),
        help="Ultralytics run output directory",
    )
    parser.add_argument(
        "--name",
        type=str,
        default="ufm_custom",
        help="Run name under project/",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="",
        help="cuda device id or 'cpu' (empty = auto)",
    )
    parser.add_argument(
        "--mosaic",
        type=float,
        default=1.0,
        help="Mosaic augmentation (set 0 on low-RAM CPUs)",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=0,
        help="Dataloader workers (0 safest on Windows/low RAM)",
    )
    return parser.parse_args()


def count_labeled_images(data_yaml: Path) -> tuple[int, int]:
    """Return (train_count, val_count) of label files present."""
    base = data_yaml.parent
    train_labels = [
        p
        for p in (base / "labels" / "train").glob("*.txt")
        if p.stat().st_size > 0
    ]
    val_labels = [
        p
        for p in (base / "labels" / "val").glob("*.txt")
        if p.stat().st_size > 0
    ]
    return len(train_labels), len(val_labels)


def write_resolved_data_yaml(data_yaml: Path) -> Path:
    """
    Ultralytics resolves `path: .` from the process CWD, not the yaml folder.
    Write a sibling file with an absolute path so train/val resolve correctly.
    """
    import yaml

    text = data_yaml.read_text(encoding="utf-8")
    try:
        data = yaml.safe_load(text) or {}
    except Exception:
        data = {}
    data["path"] = str(data_yaml.parent.resolve()).replace("\\", "/")
    if "train" not in data:
        data["train"] = "images/train"
    if "val" not in data:
        data["val"] = "images/val"
    out = data_yaml.parent / "_data_resolved.yaml"
    out.write_text(
        "# Auto-generated by train_yolo.py — do not edit by hand\n"
        + yaml.safe_dump(data, sort_keys=False),
        encoding="utf-8",
    )
    return out


def main() -> None:
    args = parse_args()
    data_yaml = Path(args.data).resolve()
    if not data_yaml.is_file():
        raise SystemExit(f"Dataset config not found: {data_yaml}")

    train_n, val_n = count_labeled_images(data_yaml)
    if train_n == 0:
        raise SystemExit(
            "No non-empty training labels found in dataset/ufm/labels/train/. "
            "Run: python ai/seed_ufm_dataset.py --from-video\n"
            "Then fix labels (see ai/dataset/README.md)."
        )
    if val_n == 0:
        print(
            "WARNING: no non-empty validation labels in labels/val/ — "
            "copying train split for val is recommended."
        )

    resolved = write_resolved_data_yaml(data_yaml)
    print(f"Dataset: {data_yaml}")
    print(f"Resolved: {resolved}")
    print(f"Non-empty labels: train={train_n}, val={val_n}")
    print(f"Base weights: {args.base_weights}")
    print(f"Epochs={args.epochs}, imgsz={args.imgsz}, batch={args.batch}")

    model = YOLO(args.base_weights)
    results = model.train(
        data=str(resolved),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        project=args.project,
        name=args.name,
        device=args.device or None,
        exist_ok=True,
        mosaic=args.mosaic,
        workers=args.workers,
        cache=False,
    )

    save_dir = Path(results.save_dir) if hasattr(results, "save_dir") else None
    best = save_dir / "weights" / "best.pt" if save_dir else None
    print()
    if best and best.is_file():
        print(f"Training complete. Best weights: {best}")
        print(
            "Use with: python ai/test_detector.py "
            f"--source ai/samples/phone_under_desk.jpg"
        )
    else:
        print("Training finished. Check ai/runs/train/ for weights.")


if __name__ == "__main__":
    main()
